#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinDBCart.Resource", IsApplication=true)]

namespace XamarinDBCart
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int list = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050012
			public const int aboutButton = 2131034130;
			
			// aapt resource value: 0x7f050009
			public const int addButton = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int addItem = 2131034131;
			
			// aapt resource value: 0x7f050001
			public const int calltextView = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int cancelButton = 2131034120;
			
			// aapt resource value: 0x7f050011
			public const int cartButton = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int cartListView = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int itemDesc = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int itemDescriptionTextView = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int itemImageView = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int itemListView = 2131034128;
			
			// aapt resource value: 0x7f050005
			public const int itemName = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int itemNameTextView = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int itemPrice = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int itemPriceTextView = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int logoImageView = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int mainScrollview = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int menuButton = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int orderButton = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int phoneNumberTextView = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddItemView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CartMenuView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ItemDetailView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ItemMenuView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ItemRowView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainMenu = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
